### ISSUE TITLE
parser.parseStatement does not follow grammar for parsing parameters

### ISSUE THREAD

**Issue by bonnyr** [tufanbarisyildirim/gonginx#1]
The grammar outlined in the documentation suggests that parsing directives follows these rules:
```
directive   : Keyword [parameters] (semicolon|block)
            ;
parameters  : parameters keyword
            ;
keyword     : Keyword 
            | Variable 
            | Regex
            ;
```

This is implemented in parseStatement and the code iterates over tokens and checks for quoted string or keyword tokens, but not for variables even though the `keyword` production above clearly indicates Variables are allowed.

This can be easily checked by trying to parse the following fragment:
```

...
http {
   ...
    map $host $clientname {
        default -;
    }
  ...
}
```

In this case the parameters are variables and cause panic during parse

**Comment by tufanbarisyildirim** [comment]
Thanks for reporting @bonnyr 
Confirmed that it does not accept variables as directive parameter.
I would be happy to review and merge if you have a solution for it. I will also fix when I have time if you don't.
