### ISSUE TITLE
NewParser use os.Open  and how to close it

### ISSUE THREAD

**Issue by ixqbar** [tufanbarisyildirim/gonginx#28]
NewParser use os.Open  and how to close it ?

<img width="706" alt="image" src="https://github.com/tufanbarisyildirim/gonginx/assets/960982/a23c8001-c4fc-4512-8398-3928b1855d59">

**Comment by tufanbarisyildirim** [comment]
good catch with my rookie mistake, I would happily merge if you want to fix it @ixqbar .

**Comment by berejant** [comment]
@tufanbarisyildirim I pushed merge request to fix it. #29

**Comment by tufanbarisyildirim** [comment]
Thanks @berejant
