### ISSUE TITLE
Version tag is wrong

### ISSUE THREAD

**Issue by devhaozi** [tufanbarisyildirim/gonginx#52]
An error message was reported when trying to get version v2.0.1 using the `go get` command:

```bash
go get github.com/tufanbarisyildirim/gonginx@v2.0.1
go: github.com/tufanbarisyildirim/gonginx@v2.0.1: invalid version: unknown revision v2.0.1
```

It seems that the tag is wrong. The correct tag should be `v2.0.1`, not `2.0.1`.

**Comment by tufanbarisyildirim** [comment]
hi @devhaozi thanks for reporting, just figured that the tag is `2.0.1`  that's a typo. I will try to create tags with v in next releases.
