### ISSUE TITLE
How to keep the data in multi-line configuration

### ISSUE THREAD

**Issue by ssz1025** [tufanbarisyildirim/gonginx#54]
![image](https://github.com/user-attachments/assets/636f699f-cf87-410e-88ef-07e0aa5dec22)
![image](https://github.com/user-attachments/assets/b1a82260-9acf-4e23-9fa1-f4ae5e4a3db9)

log_format main '$remote_addr - $remote_user [$time_local] "$request" ' 
					'$status $body_bytes_sent "$http_referer" '
					'"$http_user_agent" "$http_x_forwarded_for" "$request_time" "$host" ';
					
My original nginx configuration is multi-line, and after parsing it, it becomes one line. How to keep the data in multi-line configuration;
Note: The spaces and line breaks I use are\t \n

**Comment by mofantor** [comment]
regarding this request, I have already submitted a PR:
[#54 Keep parameters in their relative lines when in multi-line configuration.](https://github.com/tufanbarisyildirim/gonginx/pull/61)
check it out

**Comment by tufanbarisyildirim** [comment]
thanks @mofantor , let's polish it and we merge
